<?php
ob_start();
require 'PHPMailer/PHPMailerAutoload.php';

include "create_lead_data_pdf_for_email.php";

$link = $path;

$mail = new PHPMailer;
$mail->setFrom('indet@onlineinsure.co.nz', 'INDET');
$debugging_mode = false;

if ($debugging_mode) {
  $mail->addAddress('jesse@eliteinsure.co.nz', 'Test');
} else {
  $mail->addAddress('admin@eliteinsure.co.nz', 'Admin');
  $mail->addCC('jing@eliteinsure.co.nz', 'Lead Telemarketer');
  $mail->addCC('kennith@eliteinsure.co.nz', 'Lead Telemarketer');
  $mail->addCC('qualitycontrol@eliteinsure.co.nz', 'Quality Control');
  $mail->addAddress('junior.admin@eliteinsure.co.nz', 'Junior Admin');
  $mail->addBCC('jesse@eliteinsure.co.nz', 'IT Support');
}

$mail->addReplyTo('indet@onlineinsure.co.nz', 'INDET');
$mail->Subject  = "Telemarketing Lead - " . $lead_data->grade;
$mail->Body     = "A lead was generated by " . $lead_data->agent . ", please see the attached PDF to get further information." . "
    \r\nAppointment Information:
      \r\nVenue:" . $lead_data->venue . "
      \r\nDate:" . $lead_data->appointment_date . "
      \r\nTime:" . $lead_data->appointment_hour . ":" . $lead_data->appointment_minute . " " . $lead_data->appointment_period;

$mail->addAttachment($link);
if (!$mail->send()) {
  echo 'Message could not be sent.<br>';
  echo 'Mailer Error: ' . $mail->ErrorInfo;
} else {
  echo "Message sent";
}
ob_end_flush();
